spring:
  application:
    name: apache-beam

input:
  path: "pg1661.txt"

output:
  path: "wordCount.txt"

cloud:
  options:
    runner: DataflowRunner
    #project: your-gcp-project-id
    #region: us-central1
    #tempLocation: gs://your-bucket/temp
    # These are the specific keys for scaling
    numWorkers: 5
    maxNumWorkers: 10
    workerMachineType: n1-standard-2