# --- STAGE 1: Build the Shadow JAR for local ---
FROM gradle:9.4.1-jdk21-alpine AS builder

# Set the working directory
WORKDIR /home/gradle/project

# Copy only the gradle files first to leverage Docker cache for dependencies
COPY gradlew build.gradle settings.gradle ./
COPY gradle ./gradle

# Download dependencies (this layer will be cached)
RUN ./gradlew dependencies --no-daemon || true

# Copy the source code
COPY src ./src

# Build the Shadow JAR for local (Fat JAR)
RUN ./gradlew shadowJarLocal --no-daemon

# --- STAGE 2: Package the Flex Template ---
# Use the official Google Dataflow launcher base image
FROM gcr.io/dataflow-templates-base/java21-template-launcher-base:latest

ENV FLEX_TEMPLATE_JAVA_CLASSPATH="/template/apache-beam.jar"
ENV FLEX_TEMPLATE_JAVA_MAIN_CLASS="org.example.apache_beam.pipelines.LocalTextAnalyzerToTextPipeline"

# Copy the JAR from the builder stage
COPY --from=builder /home/gradle/project/build/libs/apache-beam.jar ${FLEX_TEMPLATE_JAVA_CLASSPATH}

WORKDIR /template
COPY configs/localParams.json ./configs/localParams.json

# 3. Use the Metadata environment variable to point to the parameters
# This tells the launcher to use this file for default parameters
ENV FLEX_TEMPLATE_METADATA_FILE="/template/configs/localParams.json"

# The standard entrypoint for Google Cloud Dataflow Flex Templates
ENTRYPOINT ["/opt/google/dataflow/java-template-launcher"]