steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/gcs-to-bq-template:latest',
      '-f', 'dockerfiles/Dockerfile-gcs-to-bq',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/gcs-to-bq-template:latest'
