steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/textanalyzer-489509/gcs-to-gcs-template:latest',
      '-f', 'dockerfiles/Dockerfile-gcs-to-gcs',
      '.'
    ]
images:
  - 'gcr.io/textanalyzer-489509/gcs-to-gcs-template:latest'
